# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bombshell/all/bombshell.rbi
#
# bombshell-0.1.6
module Bombshell
  def launch(shell); end
  def self.launch(shell); end
end
module Bombshell::Shell
  def _prompt; end
  def get_binding; end
  def self.included(base); end
  def to_s; end
  include Bombshell::Shell::Commands
end
module Bombshell::Shell::Commands
  def method_missing(*args); end
  def quit; end
end
module Bombshell::Shell::ClassMethods
  def before_launch(&callback); end
  def bombshell_prompt; end
  def having_launched(&callback); end
  def launch(*arguments); end
  def prompt_with(p = nil, &prompt); end
end
class Bombshell::Completor
  def complete(fragment); end
  def initialize(shell); end
  def self.filter(m); end
  def shell; end
end
class Bombshell::Environment
end
module IRB
  def self.start_session(binding); end
end
