# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/wirble/all/wirble.rbi
#
# wirble-0.1.3
module Wirble
  def self.colorize(custom_colors = nil); end
  def self.init(opt = nil); end
end
module Wirble::Internals
  def self.init(opt = nil); end
  def self.init_libraries; end
  def self.init_prompt; end
end
class Wirble::History
  def cfg(key); end
  def initialize(opt = nil); end
  def load_history; end
  def save_history; end
  def say(*args); end
end
module Wirble::Colorize
  def self.colorize(str); end
  def self.colorize_string(str, color); end
  def self.colors; end
  def self.colors=(hash); end
  def self.disable; end
  def self.enable(custom_colors = nil); end
end
module Wirble::Colorize::Tokenizer
  def self.tokenize(str); end
end
module Wirble::Colorize::Color
  def self.escape(key); end
end
module Wirble::Shortcuts
  def po(o); end
  def poc(o); end
end
module Wirble::RiShortcut
  def self.init; end
end
