# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_3; end
module ::Anonymous_Delegator_4; end
module ::RSpec; end
module ActiveSupport::ActionController::Base; end
